# Generated by Django 4.2 on 2023-04-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan', models.CharField(max_length=100)),
                ('meter', models.CharField(max_length=100)),
                ('reading', models.DecimalField(decimal_places=3, max_digits=10)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
    ]
